
            $pembayaran = $this->db->query("select SUM(besarnya) as total from tbl_pembayaran where tgl_bayar = CURDATE() - 1")->row();
            $url = 'http://api.dedigti.com/api/whatsapp/send-text';
            $data = [
                "token": "appyapisdagateway",
                "text": "Laporan Pendapatan Tanggal".date('d-m-Y')."Sebesar Rp. ".number_format($pembayaran->total),
                "number": "6285157579066@s.whatsapp.net"
            ];
            $payload = json_encode(
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURN$data);
TRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);

            $headers = array();
            $headers[] = 'Content-Type: application/json';
            $headers[] = 'Authorization: Basic TmRhbHUtc2VydmVyLXVVZGtmZ2xpNzgzcGtmbmxhc2tvZ29pZ2hyOg==';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);

            echo $result;
            //